### ISSUE TITLE
Add clipboard to code blocks

### ISSUE THREAD

**Issue by satyarohith** [denoland/manual#653] opened 2023-05-15 09:59 UTC
Better user experience if we can click and paste instead of select, copy and paste.

I expected the code blocks to have clipboard shortcut when clicked on "installation" button at https://deno.com/runtime

<img width="861" alt="CleanShot 2023-05-15 at 15 29 08@2x" src="https://github.com/denoland/manual/assets/29819102/8f24eafd-62c7-4040-9e08-2b0c44c50c3c">

rustup.rs has clipboard and it's click & paste:

<img width="929" alt="CleanShot 2023-05-15 at 15 34 20@2x" src="https://github.com/denoland/manual/assets/29819102/e5944a5e-e63c-4f9e-b111-32dc4c03751b">

**Comment by crowlKats** [comment] 2023-05-15 10:08
Duplicate of denoland/dotland#2336

**Closed by crowlKats** 2023-05-15 10:08 UTC
