### ISSUE TITLE
proc documentation: "Node requires node_modules and npm" is not true and correct

### ISSUE THREAD

**Issue by guest271314** [denoland/manual#512] opened 2022-12-31 17:20 UTC
In https://deno.land/x/proc@0.19.9 this claim is made

> Node requires `node_modules` and `npm`

I fetch the Node.js nightly binary release, extract `node` executable and run that extracted `node` executable without using `npm` or `node_modules` whatsoever https://github.com/guest271314/download-node-nightly-executable.

**Comment by bartlomieju** [comment] 2022-12-31 18:38
This os a third party project, how is that related to Deno's manual?

**Comment by guest271314** [comment] 2022-12-31 19:28
> This is description of a third party project, how is that related to Deno's manual?

Because that claim is on your Web site https://deno.land/x/proc@0.19.9?

**Comment by guest271314** [comment] 2022-12-31 19:37
@bartlomieju I let the author of that code know the same thing https://github.com/j50n/deno-proc/issues/29. 

If this is not the correct repository to file such an issue, kindly transfer this issue to the repository under Deno which is appropriate.

I'm just trying to let the relevant parties know there is a claim at large printed in documentation related to Deno that is not true and correct.

The claim has your name on it. Up to you if that is important to you or not. 

I don't think the claim is intentionally incorrect, incorrect nonetheless.

Accurate documentation is important to me. I vet all claims in specifications and documentations, without exception.

**Comment by bartlomieju** [comment] 2023-01-02 23:22
> @bartlomieju I let the author of that code know the same thing [j50n/deno-proc#29](https://github.com/j50n/deno-proc/issues/29).
> 

That should be enough, thanks.

> If this is not the correct repository to file such an issue, kindly transfer this issue to the repository under Deno which is appropriate.
> I'm just trying to let the relevant parties know there is a claim at large printed in documentation related to Deno that is not true and correct.
> 
> The claim has your name on it. Up to you if that is important to you or not.
> 
> I don't think the claim is intentionally incorrect, incorrect nonetheless.
> 
> Accurate documentation is important to me. I vet all claims in specifications and documentations, without exception.

There's no other repository, it's a claim in documentation of third party module that is not affiliated with Deno in any way - we don't moderate the content of these libraries unless they are hateful. I'm gonna close this issue for now, thanks for reporting.

**Closed by bartlomieju** 2023-01-02 23:22 UTC

**Comment by guest271314** [comment] 2023-01-03 01:54
Good to know. I won't rely on any documentation posted on the Web site https://deno.land/, as it is evidently completely unvetted. Thanks.

**Comment by guest271314** [comment] 2023-01-03 02:00
Ahh, you have the x Web site https://deno.land/x. And are claiming that is where third-party code is posted. Yet the origin is https://deno.land/. Clearly that can lead to confusion. I would host that code on its own domain. Here I am thinking that is your endoresed Web site. Hard to disambiguate third-party code and claims from yourself when you host third-party code and claims on the same origin...

**Comment by guest271314** [comment] 2023-01-03 02:09
> that is not affiliated with Deno in any way

Yes, it is. You host the claim and code on your Web site. Rethink that decision.

**Comment by dsherret** [comment] 2023-01-03 02:48
GitHub should rethink hosting your comments.

**Comment by guest271314** [comment] 2023-01-03 02:50
> GitHub should rethink hosting your comments.

Funny.

I'm providing constructive feedback. You host third-party code and claims on your site, then try to disavow the claims as if you don't host the claims yourself.

**Comment by dsherret** [comment] 2023-01-03 02:57
I was making the point that similar to someone just posting whatever on GitHub or npm, it's not expected that the hosting provider will moderate claims as true or false.

https://deno.land/x is for third party code as mentioned at that address:

> deno.land/x is a hosting service for Deno scripts. It caches releases of open-source modules stored on GitHub and serves them at an easy-to-remember domain.

There's also a link to the repository of the source on each modules page.

**Comment by guest271314** [comment] 2023-01-03 03:10
> https://deno.land/x is for third party code as mentioned at that address:

Think about this very carefully. 

I had no idea about that "x" meaning third-party code and claims hosted by Deno that Deno officials distances themselves from.

I navigate to https://deno.land/. I search for "proc". This is on _**your**_ Web site. No "**x**" in the URL. _**Your**_ top-level Web site: https://deno.land/.

![Screenshot_2023-01-02_19-01-05](https://user-images.githubusercontent.com/4174848/210295062-dc241e0e-d2ea-4dce-8ca6-283a99dfa464.png)

I click on the "proc"

![Screenshot_2023-01-02_19-02-15](https://user-images.githubusercontent.com/4174848/210295237-063f30e2-29ac-4268-a581-a315fa594cb9.png)


I never navigate to https://deno.land/x during that process to read your disclaimer. 

You need to place that disclaimer on your main Web page, and on every Web page in https://deno.land/. To avoid confusion.

I'm just trying to help you folks out. If you think you are too high and mighty to make mistakes and adjust your public facing documentation - **on your site**  - then have at it. 

I mistakenly thought Deno beauracracy and management _might_ not consider themselves above receiving constructive feedback from developers in the field, and adjust public facing documentation and claims accordingly.

I've seen it all before. Big me, little you. Not impressed. In the meantime the spurious claim is _still_ on your top-level Web site.

Feel free to ban me at any time for pointing out you have spurious claims on _your_ site. Won't be the first or last time. I don't bite my tongue or settle.

I vet all spurious claims. Without exception.

**Comment by dsherret** [comment] 2023-01-03 03:15
I don't think this is challenging to figure out. We've never had this feedback from anyone else.

**Comment by dsherret** [comment] 2023-01-03 03:20
One thing that is strange is the browser address bar didn't update. I'm not able to reproduce that behaviour.

**Comment by guest271314** [comment] 2023-01-03 03:26
> I don't think this is challenging to figure out. We've never had this feedback from anyone else.

Then you didn't carefully read what I wrote. I had no idea about that "x" meaning anything. 

If you are valuating feedback by how much of a certain type you receive then you really ain't evaluating feedback. Every feedback report is important. Else you just gloss the facts over until some unknown number of feedback reports that you internally think are the same _type_ are piled up in  corner somewhere.

I am a primary source researcher. Documentation is important. Every word therein. Dates, times, people, places, events; who; what; when; where.

I fetch `node` nightly executable in the browser. `npm` never makes it to my filesystem - I get rid of all the rest of the files and folders in Node.js nightly binary download. And no `node_modules` folder or file is anywhere on my machine.

> One thing that is strange is the browser address bar didn't update. I'm not able to reproduce that behaviour.

Update to what?

I never visited https://deno.land/x during that entire process, so never read your disclaimer.

That false information is on _your_ Web site.

Steps to reproduce:

1. Navigate to https://deno.land/;
2. Click in the Search field;
3. Search for "proc";
4. Scroll down and click the "proc" link;

Now, advise me in steps 1.-4. exactly where I ever visit https://deno.land/x to read your disclaimer?

You are missing the point entirely though.

The claim

> Node requires `node_modules` and `npm`.

is an untruth, false.

So you have to try to avoid that incontrovertible fact.

**Comment by guest271314** [comment] 2023-01-03 03:37
@dsherret See this code, notice how I extract **_only_** the `node` executable at `/\/bin\/node$/.test(file.name)`? 

I never actually _install_ `node` executable, or `deno`. I just run the nightly executable in the directory to which I write the file. Again, proving that claim **on your Web site** is spurious.

Ironically that is one of the reasons I began experimenting with Deno - because at least y'all don't ship some internal package manager and other files in the download. I just do 

```
wget --show-progress --progress=bar \
  --output-document deno.zip \
https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip && \
  unzip deno.zip && \
  rm deno.zip
```

Done.

I did try to fetch the zip in the browser, though havn't been successful, yet. That would be something to work on - make it simpler to get the binary.

```
          let [node_nightly_build] = await (
            await fetch('https://nodejs.org/download/nightly/index.json')
          ).json();
          let { version, files } = node_nightly_build;
          let node_nightly_url = `https://nodejs.org/download/nightly/${version}/node-${version}-${osArch}.tar.gz`;
          let url = `${cors_api_url}${node_nightly_url}`;
          console.log(`Fetching ${node_nightly_url}`);
          const request = (await fetch(url)).body.pipeThrough(
            new DecompressionStream('gzip')
          );
          // Download gzipped tar file and get ArrayBuffer
          const buffer = await new Response(request).arrayBuffer();
          // Decompress gzip using pako
          // Get ArrayBuffer from the Uint8Array pako returns
          // const decompressed = await pako.inflate(buffer);
          // Untar, js-untar returns a list of files
          // (See https://github.com/InvokIT/js-untar#file-object for details)
          const untarFileStream = new UntarFileStream(buffer);
          while (untarFileStream.hasNext()) {
            file = untarFileStream.next();
            if (/\/bin\/node$/.test(file.name)) {
              break;
            }
          }
          writable = await fileSystemHandle.createWritable();
          writer = writable.getWriter();
          await writer.write(file.buffer);
          await writer.close();
          new Notification('Download complete.', {
             body: `Successfully downloaded node executable ${version}`
          });
```
