### ISSUE TITLE
Add information to Setting Up for Nova

### ISSUE THREAD

**Issue by kitsonk** [denoland/manual#56] opened 2021-08-17 22:05 UTC
Should add a section about setting up for Nova editor.

@jaydenseric

**Comment by jaydenseric** [comment] 2021-08-21 01:11
I'll raise a PR for this. I've been holding off until there is a game-plan for the outstanding major bugs (all blocked by either Deno or Nova):

https://github.com/jaydenseric/nova-deno/issues

[Support for JSX and TSX](https://github.com/jaydenseric/nova-deno/issues/1) can be achieved after Deno releases [this](https://github.com/denoland/deno/pull/11755), hopefully sooner than the September 14 [v1.14.0 milestone](https://github.com/denoland/deno/milestone/24)! As soon as a Deno release is out I'll follow it up with a [Deno Nova](https://github.com/jaydenseric/nova-deno) update and the biggest usability issue will be solved.

Of [the 5 Nova bugs](https://github.com/jaydenseric/nova-deno/issues?q=is%3Aissue+is%3Aopen+label%3A%22Nova+bug%22), 2 have been acknowledged by Nova devs and are likely to be fixed in the next Nova release, which should be days or weeks away (not months) in my estimation.

Hopefully the Nova devs respond to the remaining 3 issues, the most serious relating to code actions not working:

- https://github.com/jaydenseric/nova-deno/issues/5
- https://github.com/jaydenseric/nova-deno/issues/6

If the Nova devs don't respond soon, I'll raise a PR here regardless and the Deno community will have to just lower our expectations for Nova.

Something else to note: My published [Nova Deno](https://github.com/jaydenseric/nova-deno) extension is the newest (and after spending a lot of time on the problem is in my opinion the most correct/robust), but at least two other people have also worked on Deno extensions in the past:

1. https://github.com/robb-j/nova-deno (not published)
2. https://github.com/sgwilym/nova-deno (published)

I'll raise a Deno manual PR that documents how to setup for Nova with my extension (a 1-click install), and if at some point the other authors feel confident enough about supporting theirs they can submit PRs to either additionally document theirs, or pitch why mine should be replaced.

**Closed** 2021-09-07 13:24 UTC
